name: Reusable CI Workflow

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      version:
        required: true
        type: string
        
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   

    steps:
      - name: Descargar cÃ³digo del repositorio
        uses: actions/checkout@v3

      - name: Login to GHCR
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
        run: echo "$GHCR_PAT" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Construir imagen
        run: |
          docker build -t ghcr.io/${{ github.actor }}/${{ inputs.image_name }}:${{ inputs.version }} .
      
      - name: Publicar imagen
        run: |
          docker push ghcr.io/${{ github.actor }}/${{ inputs.image_name }}:${{ inputs.version }}
          
      - name: Establecer tag como output 
        id: set_tag 
        run: |  
          echo "tag=ghcr.io/${{ github.actor }}/${{ inputs.image_name }}:${{ inputs.version }}" >> $GITHUB_OUTPUT

  usar-tag: 
    needs: build-and-push 
    runs-on: ubuntu-latest 
    steps: 
        - name: Mostrar tag 
          run: |
             echo "El tag generado es: ${{ needs.build-and-push.outputs.tag }}"
